### ISSUE TITLE
Example of usage for FaceNet

### ISSUE THREAD

**Issue by bocse** [deeplearning4j/dl4j-model-z#10]
I wanted to run the FaceNet model
( https://github.com/deeplearning4j/dl4j-model-z/blob/master/src/main/java/org/deeplearning4j/FaceNetVariant.java )

Although I understand that the training need to be done with anchor-positive-negative triplets (respectively corresponding to input1, input2, input3, I assume), I'm not sure how I can:
a) output the feature vector (I assume it's in the out of the embed1 layer?)
b) use the trained network on just one image (sending just one image results in java.lang.IllegalArgumentException: Invalid input array: network has 3 inputs, but array is of length 1 )

A brief example would answer all these questions.

Thank you

**Comment by saudet** [comment]
@crockpotveggies Got an example for this?

**Comment by crockpotveggies** [comment]
Will be releasing it as a separate project when I'm done training models.
Nothing releasable atm.

**Comment by radium226** [comment]
Hello ! Is there any news about the training / availability of this new feature? Thanks!

**Comment by crockpotveggies** [comment]
A variant of FaceNet is now available in our snapshots for the new deeplearning4j-zoo module. We have also made available a trained VGGFace model.

**Comment by saelha01** [comment]
crockpotveggies  do you have a document, link, or exmaple we can leverage?
big thanks in advance for your help

**Comment by saelha01** [comment]
I just need an example of a faceNet network where I input a pic of a face and get back the embeddings array

**Comment by crockpotveggies** [comment]
Not yet, this is on the roadmap but will not be delivered this month.

**Comment by saelha01** [comment]
hi @crockpotveggies , is there any updates on this topic. 
to recap, we were looking for dl4j example/implementation  of a faceNet network where we input a face pic of a face and get back the embeddings array.

Thanks in advance for your help

**Comment by crockpotveggies** [comment]
Please check the model zoo in 0.9.0 release, there is a VGG Face network
there that you can use for this purpose. That is as far as we have for now.
