### ISSUE TITLE
FaceNetVariant working example

### ISSUE THREAD

**Issue by mhashem** [deeplearning4j/dl4j-model-z#13]
Hello, I am sorry for opening an issue while it is not so, but I am new to deeplearning, I have a research about face recognition, and I came across your implementation of [FaceNetVariant.java](https://github.com/deeplearning4j/dl4j-model-z/blob/master/src/main/java/org/deeplearning4j/FaceNetVariant.java), could you please advise of any working example? how can I use this Java implementation of **facenet** to generate face embeddings vector? Thanks

**Comment by blackredscarf** [comment]
@crockpotveggies
I find the effect of vggface is not well. I want to know when we can use the pretrained InceptionResNetV1(A variant of the original FaceNet) ?

**Comment by crockpotveggies** [comment]
Hi folks, this is an outdated repo and we've migrated everything to deeplearning4j-zoo. Can you confirm which one that you're using? Going to close this issue for now and leave a note in the README.
