### ISSUE TITLE
GoogLeNet model does not build

### ISSUE THREAD

**Issue by antikantian** [deeplearning4j/dl4j-model-z#4]
There are some issues with the architecture of the GoogLeNet model, specifically inconsistencies between the implementation and the reference paper.  In particular, there are some errors with the output dimensions of some of the later inception model convolutions, as well as some extra layers towards the end, all of which result in an IllegalStateException due to a cycle in the graph.  

I [rewrote this implementation](https://gist.github.com/antikantian/f77e91f924614348ea8f64731437930d); however, my version is in scala.  If you want, I can make the appropriate changes in java and send a pull request once I get everything working and tested.

**Comment by nyghtowl** [comment]
@antikantian a PR would be great if you are still offering

**Comment by crockpotveggies** [comment]
Apologies for being 2 years late on this, but we've migrated the zoo to the main deeplearning4j project https://github.com/deeplearning4j/deeplearning4j

If you're having further issues please open a new issue there. Thanks.
