### ISSUE TITLE
Network weights?

### ISSUE THREAD

**Issue by quertenmont** [deeplearning4j/dl4j-model-z#5]
Hello,

I am new to DL4j, so apologies if my question doesn't make sense.
If I understand well, this package provide the network configuration for some of the most famous and successful conv net models.  However, what is challenging is the training of these models rather than their configuration  and I don't see anywhere in DL4J code how we can actually load the "pre-trained" weights for these famous models.

Is this something that you are planning to add later so we can retrain only the latest layers of these models ?

Thanks in advance,
Loic

**Comment by danimateos** [comment]
Hi! I also would be very interested in this. Right now I'm trying to do transfer learning putting a new model on top of the bottleneck features from VGG16, the point being precisely to avoid training VGG16 myself. This requires importing weights, which are available [here](https://gist.github.com/baraldilorenzo/07d7802847aaad0a35d3), but there's no way of doing that now, is there?

I know model importing is being worked on, by @turambar. @tomthetrainer put a tutorial on this [here](https://deeplearning4j.org/model-import-keras). I tried to go that route, but I get `org.deeplearning4j.nn.modelimport.keras.InvalidKerasConfigurationException: Unsupported keras layer type ZeroPadding2D.`

Any chance both workstreams could be combined somehow? I'm totally willing to contribute but I'm a Scala guy, not Java...

**Comment by turambar** [comment]
@quertenmont @danimateos this is indirectly related to [Keras model import](https://github.com/deeplearning4j/deeplearning4j/tree/master/deeplearning4j-modelimport/src/main/java/org/deeplearning4j/nn/modelimport/keras). The VGG models currently in the zoo are DL4J custom configurations for training. However, Keras model import currently in master (and included in the upcoming 0.7.3 release) can successfully import [pretrained VGG models from Keras](https://github.com/fchollet/deep-learning-models/blob/master/vgg16.py). We will soon provide examples of the import process in [dl4j-examples](https://github.com/deeplearning4j/dl4j-examples) and may thereafter directly host pretrained VGG models here. @eraly knows more.

**Comment by crockpotveggies** [comment]
Apologies for being 2 years late on this, but we've migrated the zoo to the main deeplearning4j project https://github.com/deeplearning4j/deeplearning4j

If you're having further issues please open a new issue there. Thanks.
